In [19]:
import numpy as np
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
arr[8]

8

In [21]:
arr[1:5]

array([1, 2, 3, 4])

In [22]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [23]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [24]:
arr[0:5] = 100

In [25]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [26]:
slice_of_arr = arr[0:6]
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [27]:
slice_of_arr[:] = 99

In [28]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [29]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [30]:
copy_of_arr = arr.copy()

In [31]:
copy_of_arr[:]=1000

In [32]:
copy_of_arr

array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [33]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [41]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [43]:
arr_2d[1][2]

30

In [44]:
arr_2d[1,2]

30

In [47]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [48]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [49]:
arr = np.arange(1,11)

In [50]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [55]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [56]:
 arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [57]:
arr[arr<3]

array([1, 2])

In [58]:
arr_2d = np.arange(50).reshape(5,10)

In [59]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [60]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [62]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [64]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
arr ** arr

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])

In [67]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
arr * 35

array([  0,  35,  70, 105, 140, 175, 210, 245, 280, 315, 350])

In [69]:
1/0

ZeroDivisionError: division by zero

In [70]:
arr / arr

/Users/abhaykela/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [71]:
1/arr

/Users/abhaykela/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [72]:
0/0

ZeroDivisionError: division by zero

In [73]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [74]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [75]:
np.max(arr)

10

In [76]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [77]:
np.log(arr)

/Users/abhaykela/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [80]:
np.log(arr)

/Users/abhaykela/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])