In [1]:
import numpy as np

In [2]:
a = np.array([8,10,12])

In [3]:
a

array([ 8, 10, 12])

In [16]:
b = np.array([(31.1,20,23), (1,2,3)])
b

array([[31.1, 20. , 23. ],
       [ 1. ,  2. ,  3. ]])

In [5]:
np.empty((2,3))

array([[31.1, 20. , 23. ],
       [ 1. ,  2. ,  3. ]])

In [6]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((5,3,3), dtype=np.int16)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [9]:
identity = np.eye(2)
identity

array([[1., 0.],
       [0., 1.]])

In [11]:
c = np.full((3,3),10)
c

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [12]:
d = np.arange(10,25,5)
d

array([10, 15, 20])

In [13]:
np.linspace(0,1,15)

array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
       0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
       0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ])

In [14]:
r = np.random.random((4,4))
r

array([[0.35903686, 0.1013797 , 0.76736499, 0.65487992],
       [0.47861111, 0.52886141, 0.34560198, 0.07515538],
       [0.51138855, 0.99355072, 0.85555351, 0.92926482],
       [0.13866172, 0.69775702, 0.27391879, 0.53183386]])

In [19]:
name = input("Give me your name: ")
print("Your name is " + name)

Give me your name: Abhay kela
Your name is Abhay kela


In [24]:
age = input ("Enter your age: ")
print ("Your age: " + age)

Enter your age: 18
Your age: 18


In [27]:
age = 10
if age>17:
    print ("can see a rated R movie")
elif age<17 and age>12: 
    print ("can see a rate PG-13 movie")
else: 
    print ("can only see rate PG movie")

can only see rate PG movie


In [29]:
a = 5
if a == 3: 
    print ("the variable has the value 3")
elif a!= 3: 
    print ("the varible does not have the value 3")

the varible does not have the value 3


In [1]:
import sys

x = 5
print (sys.getsizeof(x))

28


In [6]:
print(size(x))

NameError: name 'size' is not defined